pack:
	rm -rf kafka-connect-streamr
	rm -rf kafka-connect-streamr.zip
	mkdir kafka-connect-streamr
	cp manifest.json kafka-connect-streamr/manifest.json
	cp target/my-source-connector-1.0-SNAPSHOT.jar kafka-connect-streamr/kafka-connect-streamr.jar
	zip -r kafka-connect-streamr.zip kafka-connect-streamr 
	