name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
        architecture: 'x64'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify && make pack
    - uses: actions/upload-artifact@v2
      with:
        name: artifac
        path: kafka-connect-streamr.zip
